name: declare

on:
  schedule:
    - cron: '0 9,21 * * *' # runs at 09:00 UTC everyday

  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: install pre-requisites
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip xvfb libxi6 libgconf-2-4
          sudo apt-get install default-jdk

      - name: install chrome
        run: |
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install ./google-chrome-stable_current_amd64.deb

      - name: install chrome driver
        run: |
          sudo apt-get install chromium-chromedriver

      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8' # install the python version needed
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: execute py script
        env: 
          USERID: ${{ secrets.USERID }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: python TempDec.py
        